# -*- coding: utf-8 -*-
"""context_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLHZRtxYvGHoxK1amVkm6G5rZQldZu5I
"""

# 📦 Step 1: Install transformers
!pip install -q transformers

# 📥 Step 2: Import and load pipeline
from transformers import pipeline
import json

nlp = pipeline("text-classification", model="bhadresh-savani/distilbert-base-uncased-emotion")

# Load uploaded chat logs
with open("chat.json", "r") as f:
    data = json.load(f)

# Context Detection Logic
flagged = []
for msg in data:
    result = nlp(msg["message"])[0]
    if result["label"] in ["fear", "anger", "surprise"] and result["score"] > 0.7:
        flagged.append({
            **msg,
            "emotion": result["label"],
            "confidence": round(result["score"], 2)
        })

# Save result
with open("flagged_chats.json", "w") as f:
    json.dump(flagged, f, indent=2)

from google.colab import files

# ✅ Download flagged results
files.download("flagged_chats.json")

# ✅ Save the model to export and reuse offline
nlp.save_pretrained("my_context_model")

# ✅ Zip the model for download
import shutil
shutil.make_archive("my_context_model", 'zip', "my_context_model")
files.download("my_context_model.zip")

# Colab (done)
from transformers import pipeline
import joblib
classifier = pipeline("text-classification", model="bhadresh-savani/distilbert-base-uncased-emotion")
joblib.dump(classifier, "chat_context_model.pkl")
